<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="job" nsURI="http://www.misc.com/common/moplaf/job/model/0.1"
    nsPrefix="job">
  <eClassifiers xsi:type="ecore:EClass" name="JobParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//JobParameterType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="JobAttribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JobParameterType">
    <eLiterals name="JOB_PARAMETER_TYPE_INT" literal="Int"/>
    <eLiterals name="JOB_PARAMETER_TYPE_STRING" value="1" literal="String"/>
    <eLiterals name="JOB_PARAMETER_TYPE_FLOAT" value="2" literal="Float"/>
    <eLiterals name="JOB_PARAMETER_TYPE_DATE" value="3" literal="Date"/>
    <eLiterals name="JOB_PARAMETER_TYPE_ENUM" value="4" literal="Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ProgressFeedback" instanceClassName="com.misc.common.moplaf.job.ProgressFeedback"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RunContext" instanceClassName="com.misc.common.moplaf.job.RunContext"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ReturnFeedback" instanceClassName="com.misc.common.moplaf.common.ReturnFeedback"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EnabledFeedback" instanceClassName="com.misc.common.moplaf.common.EnabledFeedback"/>
  <eClassifiers xsi:type="ecore:EClass" name="RunParams">
    <eOperations name="copyParams">
      <eParameters name="other" eType="#//RunParams"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Run" eSuperTypes="#//RunParams">
    <eOperations name="reset"/>
    <eOperations name="run" eType="#//ReturnFeedback"/>
    <eOperations name="run" eType="#//ReturnFeedback">
      <eParameters name="runContext" eType="#//RunContext"/>
    </eOperations>
    <eOperations name="runAsynch">
      <eParameters name="runContext" eType="#//RunContext"/>
    </eOperations>
    <eOperations name="runAsynch">
      <eParameters name="runContext" eType="#//RunContext"/>
      <eParameters name="background" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="cancel"/>
    <eOperations name="setProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="task" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="work" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="setProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="progress" eType="#//ProgressFeedback"/>
    </eOperations>
    <eOperations name="setReturn">
      <eParameters name="feedback" eType="#//ReturnFeedback"/>
    </eOperations>
    <eOperations name="getReturn" eType="#//ReturnFeedback"/>
    <eOperations name="constructParams" eType="#//RunParams"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CancelFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ResetFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cancelled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Returned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReturnSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReturnFeedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReturnInformation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" abstract="true" eSuperTypes="#//Run">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Started" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Finished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;new Job>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobConsole" abstract="true" eSuperTypes="#//Job">
    <eOperations name="addParameter">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//JobParameterType"/>
      <eParameters name="attribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
      <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="refreshParameters"/>
    <eOperations name="getArgAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="#//Exception">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getArgAsInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        eExceptions="#//Exception">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getArgAsFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        eExceptions="#//Exception">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getArgAsDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        eExceptions="#//Exception">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getArgAsDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        eExceptions="#//Exception">
      <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="simpleDateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setArgs" eExceptions="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameters" upperBound="-1"
        eType="#//JobParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HelpText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Args" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Setter">
    <eOperations name="accept">
      <eParameters name="objectToSetFeatures" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="init">
      <eParameters name="objectToGetFeatures" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Features" upperBound="-1"
        eType="#//SetterStructuralFeature" containment="true" eOpposite="#//SetterStructuralFeature/Setter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetterStructuralFeature" abstract="true">
    <eOperations name="accept">
      <eParameters name="objectToSetFeatures" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Setter" lowerBound="1"
        eType="#//Setter" eOpposite="#//Setter/Features"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FeatureToSet" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetterAttribute" abstract="true" eSuperTypes="#//SetterStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AttributeToSet" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetterAttributeInt" eSuperTypes="#//SetterAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetterAttributeFloat" eSuperTypes="#//SetterAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamsHolder">
    <eOperations name="constructParams" eType="#//RunParams">
      <eParameters name="run" eType="#//Run"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RunsParams" upperBound="-1"
        eType="#//RunParams" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobFileHandler" abstract="true" eSuperTypes="#//Job ../../com.misc.common.moplaf.file.emf/model/file.ecore#//FileHandler"/>
  <eClassifiers xsi:type="ecore:EClass" name="Runs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Runs" upperBound="-1" eType="#//Run"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Doc" abstract="true" eSuperTypes="#//KeyIndicators">
    <eOperations name="clone" eType="#//Doc"/>
    <eOperations name="flush"/>
    <eOperations name="save"/>
    <eOperations name="load"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CloneFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FlushFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Loaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Refs" upperBound="-1" eType="#//DocRef"
        eOpposite="#//DocRef/Doc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocRef" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Doc" lowerBound="1" eType="#//Doc"
        eOpposite="#//Doc/Refs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocsHolder">
    <eOperations name="addDoc">
      <eParameters name="doc" eType="#//Doc"/>
    </eOperations>
    <eOperations name="addDocs">
      <eParameters name="docs" upperBound="-1" eType="#//Doc"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Docs" upperBound="-1" eType="#//DocInDocsHolder"
        containment="true" eOpposite="#//DocInDocsHolder/DocsHolder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundDoc" eSuperTypes="#//Doc #//DocsHolder"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocInDocsHolder" eSuperTypes="#//DocRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DocsHolder" lowerBound="1"
        eType="#//DocsHolder" eOpposite="#//DocsHolder/Docs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="#//Run">
    <eOperations name="isValidInput" eType="#//EnabledFeedback">
      <eParameters name="doc" eType="#//Doc"/>
    </eOperations>
    <eOperations name="isValidOutput" eType="#//EnabledFeedback">
      <eParameters name="doc" eType="#//Doc"/>
    </eOperations>
    <eOperations name="addInputDoc">
      <eParameters name="doc" eType="#//Doc"/>
    </eOperations>
    <eOperations name="addInputDocs">
      <eParameters name="docs" upperBound="-1" eType="#//Doc"/>
    </eOperations>
    <eOperations name="initOutputs"/>
    <eOperations name="clone" eType="#//Task"/>
    <eOperations name="addOutputDoc">
      <eParameters name="doc" eType="#//Doc"/>
    </eOperations>
    <eOperations name="addOutputDocs">
      <eParameters name="docs" upperBound="-1" eType="#//Doc"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CloneFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;new Task>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Inputs" upperBound="-1"
        eType="#//TaskInput" containment="true" eOpposite="#//TaskInput/Consumer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Outputs" upperBound="-1"
        eType="#//TaskOutput" containment="true" eOpposite="#//TaskOutput/Producer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainTask" abstract="true" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Domain" lowerBound="1"
        eType="#//TaskDomain" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDoc" abstract="true" eSuperTypes="#//DocRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskInput" eSuperTypes="#//TaskDoc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consumer" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/Inputs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskOutput" eSuperTypes="#//TaskDoc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Producer" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/Outputs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tasks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Docs">
    <eOperations name="garbageCollect"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Docs" upperBound="-1" eType="#//Doc"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDomain" eSuperTypes="#//Docs #//Tasks">
    <eOperations name="getNewTasks" upperBound="-1" eType="#//Task">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return an exemplar of every task type supported by this TaskDomain."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyIndicators">
    <eOperations name="getKeyIndicator" eType="#//KeyIndicator">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOrCreateKeyIndicator" eType="#//KeyIndicator">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="updateKeyIndicator" eType="#//KeyIndicator">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="refreshKeyIndicators"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Indicators" upperBound="-1"
        eType="#//KeyIndicator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyIndicator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
