<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spreadsheetcsv" nsURI="http://www.misc.com/common/moplaf/spreadsheet/csv/model/0.1"
    nsPrefix="spshcsv">
  <eClassifiers xsi:type="ecore:EClass" name="SpreadsheetCSV" eSuperTypes="../../com.misc.common.moplaf.spreadsheet.emf/model/spreadsheet.ecore#//Spreadsheet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Format" eType="#//CSVFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EscapeCharacter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RecordSeparator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuoteCharacter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSVFormat">
    <eLiterals name="EnumLiteralCsvFormat_DEFAULT" literal="DEFAULT"/>
    <eLiterals name="EnumLiteralCsvFormat_EXCEL" value="1" literal="EXCEL"/>
    <eLiterals name="EnumLiteralCsvFormat_MYSQL" value="2" literal="MYSQL"/>
    <eLiterals name="EnumLiteralCsvFormat_RFC4180" value="3" literal="RFC4180"/>
    <eLiterals name="EnumLiteralCsvFormat_TDF" value="4" literal="TDF"/>
  </eClassifiers>
</ecore:EPackage>
