<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solverglpk" nsURI="http://www.misc.com/common/moplaf/solver/glpk/model/0.1"
    nsPrefix="svrgl">
  <eClassifiers xsi:type="ecore:EClass" name="SolverGLPK" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//SolverLp ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//ILpWriter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnableFeasibilityPump"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnableGomoryCuts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnableGeneratingMixedCoverCuts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnableGeneratingCliqueCuts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnableMixedIntegerRoundingCuts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
