<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Report" nsURI="http://www.misc.com/common/moplaf/report/model/0.1"
    nsPrefix="rpt">
  <eClassifiers xsi:type="ecore:EClass" name="ReportAbstract" abstract="true">
    <eOperations name="generate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="render"/>
    <eOperations name="write"/>
    <eOperations name="getContext" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eOperations name="run"/>
    <eOperations name="getReportDesignFileURL" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="URL for the report file.&#xD;&#xA;Use for instance platform:/plugin/&lt;bundleID>/&lt;path_in_bundle>/&lt;file_Name>"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Engine" eType="#//ReportEngine"
        defaultValueLiteral="Birt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Format" eType="#//ReportRenderFormat"
        defaultValueLiteral="pdf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Generated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OutputFilePath" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="/home/michel/tmp/output"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastGenerated" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunMode" eType="#//ReportRunMode"
        defaultValueLiteral="GenerateAndRender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mayBeRun" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="false"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mayBeRunFeedback" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReportEngine">
    <eLiterals name="EnumReportEngineBirt" literal="Birt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReportRenderFormat">
    <eLiterals name="EnumRenderFormatPdf" literal="pdf"/>
    <eLiterals name="EnumRederFormatHtml" value="1" literal="html"/>
    <eLiterals name="EnumRenderFormatXls" value="2" literal="xls"/>
    <eLiterals name="EnumRenderFormatXlsx" value="4" literal="xlsx"/>
    <eLiterals name="EnumRenderFormatDoc" value="5" literal="doc"/>
    <eLiterals name="EnumRenderFormatDocx" value="3" literal="docx"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReportRunMode">
    <eLiterals name="EnumGenerateOnly" literal="GenerateOnly"/>
    <eLiterals name="EnumRenderOnly" value="1" literal="RenderOnly"/>
    <eLiterals name="EnumWriteOnly" value="2" literal="WriteOnly"/>
    <eLiterals name="EnumGenerateAndRender" value="3" literal="GenerateAndRender"/>
    <eLiterals name="EnumGenerateAndWrite" value="4" literal="GenerateAndWrite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
</ecore:EPackage>
