<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kml" nsURI="http://www.misc.com/common/moplaf/gis/kml/model/0.1"
    nsPrefix="kml">
  <eClassifiers xsi:type="ecore:EClass" name="Kml" eSuperTypes="../../com.misc.common.moplaf.file.emf/model/file.ecore#//FileReaderWriter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Feature" eType="#//Feature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Placemark" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Geometry" eType="#//Geometry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Placemark" lowerBound="1"
        eType="#//Placemark" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Coordinates" eType="#//Coordinates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineString" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Coordinates" upperBound="-1"
        eType="#//Coordinates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinearRing" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Coordinates" upperBound="-1"
        eType="#//Coordinates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Coordinates" instanceClassName="com.misc.common.moplaf.common.Coordinates"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiGeometry" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Geometries" upperBound="-1"
        eType="#//Geometry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="OuterBoundary" lowerBound="1"
        eType="#//LinearRing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InnerBoundaries" upperBound="-1"
        eType="#//LinearRing" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
