<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kml" nsURI="http://www.misc.com/common/moplaf/gis/kml/model/0.1"
    nsPrefix="kml">
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Placemark" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Geometry" eType="#//Geometry"
        containment="true" eOpposite="#//Geometry/Placemark"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Placemark" lowerBound="1"
        eType="#//Placemark" eOpposite="#//Placemark/Geometry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Elevation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kml" eSuperTypes="../../com.misc.common.moplaf.file.emf/model/file.ecore#//FileReader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Files" eType="ecore:EClass ../../com.misc.common.moplaf.file.emf/model/file.ecore#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Feature" eType="#//Feature"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
