<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solver" nsURI="http://www.misc.com/common/moplaf/solver/model/0.1"
    nsPrefix="svr">
  <eClassifiers xsi:type="ecore:EEnum" name="EnumLpVarType">
    <eLiterals name="EnumLiteralLpVarInteger" literal="Integer"/>
    <eLiterals name="EnumLiteralLpVarReal" value="1" literal="Real"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumLpConsType">
    <eLiterals name="EnumLiteralLpConsEqual" literal="Equal"/>
    <eLiterals name="EnumLiteralLpConsSmallerOrEqual" value="1" literal="SmallerOrEqual"/>
    <eLiterals name="EnumLiteralLpConsBiggerOrEqual" value="2" literal="BiggerOrEqual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumObjectiveType">
    <eLiterals name="Minimum"/>
    <eLiterals name="Maximum" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumSolverLogLevel">
    <eLiterals name="EnumNone" literal="None"/>
    <eLiterals name="EnumMin" value="1" literal="Min"/>
    <eLiterals name="EnumNormal" value="2" literal="Normal"/>
    <eLiterals name="EnumFull" value="3" literal="Full"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumCpLinearType">
    <eLiterals name="EnumLiteralCpLinearEqual" literal="Equal"/>
    <eLiterals name="EnumLiteralCpLinearNotEqual" value="1" literal="NotEqual"/>
    <eLiterals name="EnumLiteralCpLinearSmaller" value="2" literal="Smaller"/>
    <eLiterals name="EnumLiteralCpLinearSmallerOrEqual" value="3" literal="SmallerOrEqual"/>
    <eLiterals name="EnumLiteralCpLinearBigger" value="4" literal="Bigger"/>
    <eLiterals name="EnumLiteralCpLinearBiggerOrEqual" value="5" literal="BiggerOrEqual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumCpLogicalType">
    <eLiterals name="EnumLiteralCpLogicalOr" literal="Or"/>
    <eLiterals name="EnumLiteralCpLogicalAnd" value="1" literal="And"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator" abstract="true" eSuperTypes="../../com.misc.common.moplaf.job.emf/model/job.ecore#//Run">
    <eOperations name="generate" eType="ecore:EDataType ../../com.misc.common.moplaf.job.emf/model/job.ecore#//ReturnFeedback"/>
    <eOperations name="generateRootTuples" eExceptions="#//Exception"/>
    <eOperations name="generateTuples" eExceptions="#//Exception"/>
    <eOperations name="generateTupleXReferences" eExceptions="#//Exception"/>
    <eOperations name="generateVars" eExceptions="#//Exception"/>
    <eOperations name="generateCons" eExceptions="#//Exception"/>
    <eOperations name="generateGoals" eExceptions="#//Exception"/>
    <eOperations name="acceptSolution">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="To be implemented by the specialisation for eploiting the solver solution and making a &#xA;domain specific solution&#xA;"/>
      </eAnnotations>
      <eParameters name="solutionprovider" eType="#//Solution"/>
    </eOperations>
    <eOperations name="visitTuples" eExceptions="#//Exception">
      <eParameters name="visitor" eType="#//ITupleVisitor"/>
    </eOperations>
    <eOperations name="refreshSelectedSolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TupleRoot" upperBound="-1"
        eType="#//GeneratorTuple" changeable="false" volatile="true" transient="true"
        derived="true" eOpposite="#//GeneratorTuple/GeneratorAsRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Goals" upperBound="-1"
        eType="#//GeneratorGoal" changeable="false" volatile="true" transient="true"
        derived="true" eOpposite="#//GeneratorGoal/Generator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarBinders" upperBound="-1"
        eType="#//GeneratorVarBinder" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SolutionProvider" upperBound="-1"
        eType="#//SolutionProvider" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FootprintNofVars" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FootprintNofCons" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FootprintNofTerms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Selected" eType="#//Solution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorElement">
    <eOperations name="getGenerator" eType="#//Generator"/>
    <eOperations name="refreshSelectedSolution"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorTuple" abstract="true" eSuperTypes="#//GeneratorElement">
    <eOperations name="generateVars"/>
    <eOperations name="generateCons"/>
    <eOperations name="generateTuples"/>
    <eOperations name="visitTuples" eExceptions="#//Exception">
      <eParameters name="visitor" eType="#//ITupleVisitor"/>
    </eOperations>
    <eOperations name="generateXReferences"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GeneratorAsRoot" eType="#//Generator"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="#//Generator/TupleRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TupleElement" upperBound="-1"
        eType="#//GeneratorTuple" changeable="false" volatile="true" transient="true"
        derived="true" eOpposite="#//GeneratorTuple/TupleContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TupleContainer" eType="#//GeneratorTuple"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="#//GeneratorTuple/TupleElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" upperBound="-1" eType="#//GeneratorVar"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Cons" upperBound="-1" eType="#//GeneratorCons"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Members" upperBound="-1"
        eType="#//GeneratorTupleMember" changeable="false" volatile="true" transient="true"
        derived="true" eOpposite="#//GeneratorTupleMember/Tuple"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorTupleMember" abstract="true"
      eSuperTypes="#//GeneratorElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tuple" eType="#//GeneratorTuple"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="#//GeneratorTuple/Members"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectedSolutionDisplay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorVar" abstract="true" eSuperTypes="#//GeneratorTupleMember">
    <eOperations name="getSolutionVar" eType="#//SolutionVar">
      <eParameters name="solution" eType="#//Solution"/>
    </eOperations>
    <eOperations name="isSolutionOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="solver" eType="#//Solution"/>
    </eOperations>
    <eOperations name="isSolutionZero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="solver" eType="#//Solution"/>
    </eOperations>
    <eOperations name="getSolutionValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="solver" eType="#//Solution"/>
    </eOperations>
    <eOperations name="build" eExceptions="#//Exception">
      <eParameters name="builder" eType="#//Solver"/>
      <eParameters name="modifier" eType="#//SolverVarBinder"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" upperBound="-1"
        eType="#//SolutionVar" eOpposite="#//SolutionVar/var"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectedSolutionValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpVar" eSuperTypes="#//GeneratorVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" lowerBound="1" eType="#//EnumLpVarType"
        defaultValueLiteral="Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpTerm" upperBound="-1"
        eType="#//GeneratorLpTerm" eOpposite="#//GeneratorLpTerm/LpVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCons" abstract="true" eSuperTypes="#//GeneratorTupleMember">
    <eOperations name="getSolution" eType="#//SolutionCons">
      <eParameters name="solution" eType="#//Solution"/>
    </eOperations>
    <eOperations name="build" eExceptions="#//Exception">
      <eParameters name="builder" eType="#//Solver"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" upperBound="-1"
        eType="#//SolutionCons" eOpposite="#//SolutionCons/cons"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NofTerms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpCons" eSuperTypes="#//GeneratorCons #//GeneratorLpLinear">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//EnumLpConsType"
        defaultValueLiteral="Equal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RighHandSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpVar" lowerBound="1" eType="#//GeneratorLpVar"
        eOpposite="#//GeneratorLpVar/LpTerm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Coeff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpLinear" lowerBound="1"
        eType="#//GeneratorLpLinear" eOpposite="#//GeneratorLpLinear/LpTerm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IGeneratorTool" abstract="true" interface="true">
    <eOperations name="getGenerator" eType="#//Generator"/>
    <eOperations name="dispose"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionReader" abstract="true" eSuperTypes="#//SolutionProvider">
    <eOperations name="readSolFromFile"/>
    <eOperations name="setSolAsString">
      <eParameters name="solution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionReaderPattern" eSuperTypes="#//SolutionReader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LinePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="(\S+)\s+(\S+)\s+\(obj:(\S+)\)"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VarNameGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VarOptimalValueGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VarObjectiveCoefGroup"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILpWriter" abstract="true" interface="true"
      eSuperTypes="#//IGeneratorTool">
    <eOperations name="writeLpToFile"/>
    <eOperations name="getLpAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FileFormat" eType="#//EnumLpFileFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FileCompressed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionProvider" abstract="true" eSuperTypes="../../com.misc.common.moplaf.job.emf/model/job.ecore#//Run #//IGeneratorTool #//SolutionProviderParams">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A SolutionProvider is capable of providing a solution for a given linear formulation (a Generator).&#xA;Solution is provided as a collection of SolutionLpVars (resp. SolutionLpCons), giving properties of the solution for a particular variable GeneratorLpVar (resp. a particular constraint GeneratorLpCons)&#xA;"/>
    </eAnnotations>
    <eOperations name="solutionFactory" eType="#//Solution"/>
    <eOperations name="constructSolution" eType="#//Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" upperBound="-1"
        eType="#//Solution" containment="true" eOpposite="#//Solution/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CurrentSolutionNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solver" abstract="true" eSuperTypes="#//SolutionProvider #//SolverParams">
    <eOperations name="solve" eType="ecore:EDataType ../../com.misc.common.moplaf.job.emf/model/job.ecore#//ReturnFeedback">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Method to be called by the client to solve the lp and to produce the solution&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="buildVars" eExceptions="#//Exception"/>
    <eOperations name="buildVar" eExceptions="#//Exception">
      <eParameters name="var" eType="#//GeneratorVar"/>
    </eOperations>
    <eOperations name="buildLpVar" eExceptions="#//Exception">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
      <eParameters name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="type" eType="#//EnumLpVarType"/>
    </eOperations>
    <eOperations name="buildCons" eExceptions="#//Exception"/>
    <eOperations name="buildCons" eExceptions="#//Exception">
      <eParameters name="cons" eType="#//GeneratorCons"/>
    </eOperations>
    <eOperations name="buildLpCons" eExceptions="#//Exception">
      <eParameters name="cons" eType="#//GeneratorLpCons"/>
    </eOperations>
    <eOperations name="buildLpCons" eExceptions="#//Exception">
      <eParameters name="element" eType="#//GeneratorElement"/>
      <eParameters name="linear" eType="#//GeneratorLpLinear"/>
      <eParameters name="rhs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="type" eType="#//EnumLpConsType"/>
    </eOperations>
    <eOperations name="constructVarBinder">
      <eParameters name="binder" eType="#//GeneratorVarBinder"/>
    </eOperations>
    <eOperations name="buildGoals" eExceptions="#//Exception"/>
    <eOperations name="buildLpGoal" eExceptions="#//Exception">
      <eParameters name="goal" eType="#//GeneratorLpGoal"/>
      <eParameters name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="constructSolverGoal" eType="#//SolverGeneratorGoal">
      <eParameters name="goal" eType="#//GeneratorGoal"/>
    </eOperations>
    <eOperations name="constructSolverGoal">
      <eParameters name="previousSolution" eType="#//Solution"/>
    </eOperations>
    <eOperations name="constructSolverGoal">
      <eParameters name="previousSolver" eType="#//Solver"/>
    </eOperations>
    <eOperations name="makeSolutionGoals">
      <eParameters name="solution" eType="#//Solution"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolverLogLevel" eType="#//EnumSolverLogLevel"
        defaultValueLiteral="Normal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolverDump" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunStarted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunInitializationEnded"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunSolvingEnded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunFinalizationEnded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunDurationInitialization"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunDurationFinalization"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunDurationSolving" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunRequestTerminate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunTimeOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolUnfeasible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolFeasible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolOptimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RunInterrupted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Initializing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Solving" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Finalizing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Finished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialSolution" eType="#//Solution"
        eOpposite="#//Solution/SolverAsInitialSolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Goals" upperBound="-1"
        eType="#//SolverGoal" containment="true" eOpposite="#//SolverGoal/Solver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarBinders" upperBound="-1"
        eType="#//SolverVarBinder" containment="true" eOpposite="#//SolverVarBinder/Solver"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverCp" abstract="true" eSuperTypes="#//Solver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SearchAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLp" abstract="true" eSuperTypes="#//Solver #//SolverLpParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolOptimalityGap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverGoal" abstract="true">
    <eOperations name="buildGoal" eExceptions="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solver" lowerBound="1"
        eType="#//Solver" eOpposite="#//Solver/Goals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverGeneratorGoal" eSuperTypes="#//SolverGoal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GoalToSolve" lowerBound="1"
        eType="#//GeneratorGoal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GoalWeight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GoalBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Optimize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConstraintAbsoluteTolerance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConstraintRelativeTolerance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.000001"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eOperations name="solutionVarFactory" eType="#//SolutionVar"/>
    <eOperations name="solutionConsFactory" eType="#//SolutionCons"/>
    <eOperations name="solutionGoalFactory" eType="#//SolutionGoal"/>
    <eOperations name="constructSolutionVar" eType="#//SolutionVar">
      <eParameters name="var" eType="#//GeneratorVar"/>
    </eOperations>
    <eOperations name="constructSolutionCons" eType="#//SolutionCons">
      <eParameters name="cons" eType="#//GeneratorCons"/>
    </eOperations>
    <eOperations name="constructSolutionGoal" eType="#//SolutionGoal">
      <eParameters name="goal" eType="#//GeneratorGoal"/>
    </eOperations>
    <eOperations name="dispose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//SolutionProvider" eOpposite="#//SolutionProvider/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolutionNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SolverAsInitialSolution"
        upperBound="-1" eType="#//Solver" eOpposite="#//Solver/InitialSolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Elements" upperBound="-1"
        eType="#//SolutionElement" containment="true" eOpposite="#//SolutionElement/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vars" upperBound="-1" eType="#//SolutionVar"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Cons" upperBound="-1" eType="#//SolutionCons"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Goals" upperBound="-1"
        eType="#//SolutionGoal" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionElement">
    <eOperations name="dispose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="#//Solution" eOpposite="#//Solution/Elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionLp" eSuperTypes="#//Solution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionVar" eSuperTypes="#//SolutionElement">
    <eOperations name="isOne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isZero" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptimalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" lowerBound="1" eType="#//GeneratorVar"
        eOpposite="#//GeneratorVar/Solution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionLpVar" eSuperTypes="#//SolutionVar"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionCpVar" eSuperTypes="#//SolutionVar"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionCons" eSuperTypes="#//SolutionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cons" lowerBound="1" eType="#//GeneratorCons"
        eOpposite="#//GeneratorCons/Solution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionLpCons" eSuperTypes="#//SolutionCons"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionGoal" eSuperTypes="#//SolutionElement">
    <eOperations name="refresh"/>
    <eOperations name="constructGoal">
      <eParameters name="solver" eType="#//Solver"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Goal" lowerBound="1" eType="#//GeneratorGoal"
        eOpposite="#//GeneratorGoal/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Constrained" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Optimized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionLpGoal" eSuperTypes="#//SolutionGoal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ITupleVisitor" instanceClassName="com.misc.common.moplaf.solver.ITupleVisitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumLpFileFormat">
    <eLiterals name="FileFormatMps" literal="mps"/>
    <eLiterals name="FileFormatCplex" value="1" literal="cplex"/>
    <eLiterals name="FileFormatGams" value="2" literal="gams"/>
    <eLiterals name="FileFormatGLPK" value="4" literal="GLPK"/>
    <eLiterals name="FileFormatSav" value="3" literal="sav"/>
    <eLiterals name="FileFormatLpSolve" value="5" literal="lpsolve"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpCons" abstract="true" eSuperTypes="#//GeneratorCons">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Post" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpLinear" eSuperTypes="#//GeneratorCpCons">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//EnumCpLinearType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RightHandSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Term" upperBound="-1" eType="#//GeneratorCpLinearTerm"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpLogical" eSuperTypes="#//GeneratorCpCons">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Term" upperBound="-1" eType="#//GeneratorCpLogicalTerm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//EnumCpLogicalType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpVar" abstract="true" eSuperTypes="#//GeneratorVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpVarAtomic" eSuperTypes="#//GeneratorCpVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpLinearTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Coeff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CpVar" eType="#//GeneratorCpVarAtomic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorCpLogicalTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CpCons" eType="#//GeneratorCpCons"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorGoal" abstract="true" eSuperTypes="#//GeneratorElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A goal for the generated problem.&#xD;&#xA;A goal is expected to be directly contained to its Generator owner.&#xD;&#xA;A goal may reference a secondary goal: a subgoal."/>
    </eAnnotations>
    <eOperations name="build" eExceptions="#//Exception">
      <eParameters name="builder" eType="#//Solver"/>
      <eParameters name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="buildCons" eExceptions="#//Exception">
      <eParameters name="builder" eType="#//Solver"/>
      <eParameters name="rhs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="getSolutionGoal" eType="#//SolutionGoal">
      <eParameters name="solution" eType="#//Solution"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Generator" eType="#//Generator"
        changeable="false" volatile="true" transient="true" derived="true" eOpposite="#//Generator/Goals"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectedSolutionDisplay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" upperBound="-1"
        eType="#//SolutionGoal" eOpposite="#//SolutionGoal/Goal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ObjectiveType" eType="#//EnumObjectiveType"
        defaultValueLiteral="Maximum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpGoal" eSuperTypes="#//GeneratorGoal #//GeneratorLpLinear">
    <eOperations name="getSolutionValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="solution" eType="#//Solution"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectedSolutionValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinValueIndicative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxValueIndicative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="100000000000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpLinear">
    <eOperations name="constructTerm" eType="#//GeneratorLpTerm">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
      <eParameters name="coef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="contributeTerm" eType="#//GeneratorLpTerm">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
      <eParameters name="coef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LpTerm" upperBound="-1"
        eType="#//GeneratorLpTerm" containment="true" eOpposite="#//GeneratorLpTerm/LpLinear"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLpParams" eSuperTypes="#//SolverParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolverOptimalityTolerance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.05"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolverLinearRelaxation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverParams" eSuperTypes="#//SolutionProviderParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolverMaxDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="100">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The maximum duration (in secs) allocated to the server"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionProviderParams" eSuperTypes="../../com.misc.common.moplaf.job.emf/model/job.ecore#//RunParams">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorVarBinder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BoundVars" upperBound="-1"
        eType="#//GeneratorVar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpVarBinder" eSuperTypes="#//GeneratorVarBinder"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpVarBinderToSolution" eSuperTypes="#//GeneratorLpVarBinder"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpVarBinderToValue" eSuperTypes="#//GeneratorLpVarBinder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BoundValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverVarBinder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solver" lowerBound="1"
        eType="#//Solver" eOpposite="#//Solver/VarBinders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarBinder" eType="#//GeneratorVarBinder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLpVarBinder" eSuperTypes="#//SolverVarBinder">
    <eOperations name="getLowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
    </eOperations>
    <eOperations name="getUpperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLpVarBinderToSolution" eSuperTypes="#//SolverLpVarBinder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedSolution" lowerBound="1"
        eType="#//SolutionLp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLpVarBinderToValue" eSuperTypes="#//SolverLpVarBinder"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorLpVarBinderCustom" eSuperTypes="#//GeneratorLpVarBinder">
    <eOperations name="getLowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
      <eParameters name="solution" eType="#//SolutionLp"/>
    </eOperations>
    <eOperations name="getUpperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="var" eType="#//GeneratorLpVar"/>
      <eParameters name="solution" eType="#//SolutionLp"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolverLpVarBinderCustom" eSuperTypes="#//SolverLpVarBinder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedSolution" lowerBound="1"
        eType="#//SolutionLp"/>
  </eClassifiers>
</ecore:EPackage>
