<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagrams" nsURI="http://www.misc.com/common/moplaf/diagrams/model/0.1"
    nsPrefix="diag">
  <eClassifiers xsi:type="ecore:EClass" name="MyNode" eSuperTypes="platform:/plugin/org.eclipse.sirius.diagram/model/diagram.ecore#//DNode"/>
</ecore:EPackage>
