<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="calc" nsURI="http://www.misc.com/common/moplaf/time/continuous/calc/model/0.1"
    nsPrefix="timcontc">
  <eClassifiers xsi:type="ecore:EClass" name="ScopeDistribution" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcDistributionInitialization" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerCompositeEventRefresh" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedenCalcDistributionInitialization"
        eType="#//CalcDistributionInitialization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcDistributionChildEvents" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcDistributionProvidedEvents" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentLayerCompositeeventRefresh"
        eType="#//LayerCompositeEventRefresh"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentCalcDistributionchildEvents"
        eType="#//CalcDistributionChildEvents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcDistributionSequence" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentCalcDistributionProvidedEvents"
        eType="#//CalcDistributionProvidedEvents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerDistributionSlopes" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentCalcDistributionSequence"
        eType="#//CalcDistributionSequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerDistributionAmounts" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//ScopeDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentLayerDistributionSlopes"
        eType="#//LayerDistributionSlopes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountAbsoluteAmountAbsolute" eSuperTypes="#//CalcEventAmount"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountAbsoluteAmountAfter" eSuperTypes="#//CalcEventAmountAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountAbsoluteAtomicAmountAbsolute"
      eSuperTypes="#//CalcAmountAbsoluteAmountAbsolute"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountAbsoluteAtomicMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountDeltaAmountAfter" eSuperTypes="#//CalcEventAmountAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountDeltaAmountDelta" eSuperTypes="#//CalcEventAmount"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountDeltaAtomicAmountDelta" eSuperTypes="#//CalcAmountDeltaAmountDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcAmountDeltaAtomicMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcCapacityChangeEndAmountDelta" eSuperTypes="#//CalcAmountDeltaAmountDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcCapacityChangeEndMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcCapacityChangeStartAmountDelta"
      eSuperTypes="#//CalcAmountDeltaAmountDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcCapacityChangeStartMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcChildEventAmountAfter" eSuperTypes="#//CalcEventAmountAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcChildEventMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcChildEventSlopeAfter" eSuperTypes="#//CalcEventSlopeAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEndEventMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventAmountAfter" eSuperTypes="#//CalcEventAmount"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventAmountBefore" eSuperTypes="#//CalcEventAmount"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventMoment" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistributionEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//CalcDistributionSequence"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventSlopeAfter" eSuperTypes="#//CalcEventSlope"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventSlopeBefore" eSuperTypes="#//CalcEventSlope"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventsProviderRefreshEvents" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionEventsProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//LayerCompositeEventRefresh"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeAbsoluteAtomicMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeAbsoluteAtomicSlopeAbsolute"
      eSuperTypes="#//CalcSlopeAbsoluteSlopeAbsolute"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeAbsoluteSlopeAbsolute" eSuperTypes="#//CalcEventSlope"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeAbsoluteSlopeAfter" eSuperTypes="#//CalcEventSlopeAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeDeltaAtomicMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeDeltaAtomicSlopeDelta" eSuperTypes="#//CalcSlopeDeltaSlopeDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeDeltaSlopeAfter" eSuperTypes="#//CalcEventSlopeAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSlopeDeltaSlopeDelta" eSuperTypes="#//CalcEventSlope"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStartEventAmountAfter" eSuperTypes="#//CalcEventAmountAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStartEventMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStartEventSlopeAfter" eSuperTypes="#//CalcEventSlopeAfter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStockChangeEndMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStockChangeEndSlopeDelta" eSuperTypes="#//CalcSlopeDeltaSlopeDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStockChangeStartMoment" eSuperTypes="#//CalcEventMoment"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcStockChangeStartSlopeDelta" eSuperTypes="#//CalcSlopeDeltaSlopeDelta"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventSlope" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistributionEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//LayerDistributionSlopes"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcEventAmount" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//PropagatorFunctionDistributionEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" eType="#//LayerDistributionAmounts"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
