<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="localsearch" nsURI="http://www.misc.com/common/moplaf/localsearch/model/0.1"
    nsPrefix="ls">
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eOperations name="clone"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moves" upperBound="-1"
        eType="#//Move" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="score" lowerBound="1" eType="#//Score"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moves" upperBound="-1"
        eType="#//Move"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Move">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A move is a small change to the solution.&#xA;Small menaing a limited (constant) number of deltas with respect to the solution . &#xA;So the score a  move must be calculated in a constant time (with respect to the size of the solution).&#xA;A move is specific to a given solution (to a specific Action)."/>
    </eAnnotations>
    <eOperations name="apply"/>
    <eOperations name="revert"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="score" lowerBound="1" eType="#//Score"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Next" upperBound="-1" eType="#//Move"
        eOpposite="#//Move/Previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Previous" eType="#//Move"
        eOpposite="#//Move/Next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Score">
    <eOperations name="compare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//Score"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActionsSets" upperBound="-1"
        eType="#//ActionsSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BestSolution" eType="#//Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CurrentSolution" eType="#//Solution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionsSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxIterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaxSeconds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
