<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gis" nsURI="http://www.misc.com/common.moplaf.gis.emf" nsPrefix="gis">
  <eClassifiers xsi:type="ecore:EClass" name="GisCoordinates" eSuperTypes="#//GisLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddress" eSuperTypes="#//GisLocation">
    <eOperations name="geocode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="City" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BuildingNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geocodedAddresses" upperBound="-1"
        eType="#//GisAddressGeocoded" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedGeocodedLocation"
        eType="#//GisAddressGeocoded"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geocoder" eType="#//GisAddressGeocoder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrix">
    <eOperations name="calculate"/>
    <eOperations name="addFromLocation">
      <eParameters name="location" eType="#//GisCoordinates"/>
    </eOperations>
    <eOperations name="addToLocation">
      <eParameters name="location" eType="#//GisCoordinates"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocations" upperBound="-1"
        eType="#//GisDistanceFromLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocations" upperBound="-1"
        eType="#//GisDistanceToLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculator" eType="#//GisDistanceMatrixCalculator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocation" lowerBound="1"
        eType="#//GisDistanceFromLocation" eOpposite="#//GisDistanceFromLocation/toLocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocation" lowerBound="1"
        eType="#//GisDistanceToLocation" eOpposite="#//GisDistanceToLocation/fromLocations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceFromLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocations" upperBound="-1"
        eType="#//GisDistanceMatrixElement" containment="true" eOpposite="#//GisDistanceMatrixElement/fromLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//GisLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceToLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocations" upperBound="-1"
        eType="#//GisDistanceMatrixElement" eOpposite="#//GisDistanceMatrixElement/toLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//GisLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoded" eSuperTypes="#//GisCoordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocation" abstract="true">
    <eOperations name="getCoordinates" eType="#//GisCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoder">
    <eOperations name="geocode">
      <eParameters name="address" eType="#//GisAddress"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixCalculator">
    <eOperations name="calculate">
      <eParameters name="matrix" eType="#//GisDistanceMatrix"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
