<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gis" nsURI="http://www.misc.com/common/moplaf/gis/model/0.1"
    nsPrefix="gis">
  <eClassifiers xsi:type="ecore:EClass" name="GisCoordinatesAbstract" abstract="true"
      eSuperTypes="#//GisLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddress" abstract="true" eSuperTypes="#//GisLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CountryCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GeocodedSelected" eType="#//GisAddressGeocoded"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRoutesHolder" eSuperTypes="#//GisRouter">
    <eOperations name="update">
      <eParameters name="calculator" eType="#//GisRouteCalculator"/>
    </eOperations>
    <eOperations name="update">
      <eParameters name="calculator" eType="#//GisRouteCalculator"/>
      <eParameters name="froms" lowerBound="1" upperBound="-1" eType="#//GisLocation"/>
      <eParameters name="tos" lowerBound="1" upperBound="-1" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addFromLocation" eType="#//GisRoutesHolderFromLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addToLocation" eType="#//GisRoutesHolderToLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getFromLocation" eType="#//GisRoutesHolderFromLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getToLocation" eType="#//GisRoutesHolderToLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="refresh"/>
    <eOperations name="flush">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="flush remove all the RouteInfos from the RoutesHolder"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="clear">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="clear removes all the locations from the RoutesHolder"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromLocations" upperBound="-1"
        eType="#//GisRoutesHolderFromLocation" containment="true" eOpposite="#//GisRoutesHolderFromLocation/RoutesHolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToLocations" upperBound="-1"
        eType="#//GisRoutesHolderToLocation" containment="true" eOpposite="#//GisRoutesHolderToLocation/RoutesHolder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Symmetrical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Calculator" eType="#//GisRouteCalculator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RefreshFeedback" eType="ecore:EDataType ../../com.misc.common.moplaf.job.emf/model/job.ecore#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRoutesHolderWaypoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" lowerBound="1"
        eType="#//GisLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRoutesHolderFromLocation" eSuperTypes="#//GisRoutesHolderWaypoint">
    <eOperations name="getElement" eType="#//GisRoutesHolderElement">
      <eParameters name="toLocation" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addElement" eType="#//GisRoutesHolderElement">
      <eParameters name="toLocation" eType="#//GisRoutesHolderToLocation"/>
    </eOperations>
    <eOperations name="update">
      <eParameters name="calculator" eType="#//GisRouteCalculator"/>
    </eOperations>
    <eOperations name="refresh"/>
    <eOperations name="remove"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToLocations" upperBound="-1"
        eType="#//GisRoutesHolderElement" containment="true" eOpposite="#//GisRoutesHolderElement/FromLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutesHolder" lowerBound="1"
        eType="#//GisRoutesHolder" eOpposite="#//GisRoutesHolder/FromLocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRoutesHolderToLocation" eSuperTypes="#//GisRoutesHolderWaypoint">
    <eOperations name="getElement" eType="#//GisRoutesHolderElement">
      <eParameters name="fromLocation" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addElement" eType="#//GisRoutesHolderElement">
      <eParameters name="fromLocation" eType="#//GisRoutesHolderFromLocation"/>
    </eOperations>
    <eOperations name="update">
      <eParameters name="calculator" eType="#//GisRouteCalculator"/>
    </eOperations>
    <eOperations name="refresh"/>
    <eOperations name="remove"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromLocations" upperBound="-1"
        eType="#//GisRoutesHolderElement" eOpposite="#//GisRoutesHolderElement/ToLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutesHolder" lowerBound="1"
        eType="#//GisRoutesHolder" eOpposite="#//GisRoutesHolder/ToLocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRoutesHolderElement">
    <eOperations name="update">
      <eParameters name="calculator" eType="#//GisRouteCalculator"/>
    </eOperations>
    <eOperations name="refresh"/>
    <eOperations name="remove"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToLocation" lowerBound="1"
        eType="#//GisRoutesHolderToLocation" eOpposite="#//GisRoutesHolderToLocation/FromLocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromLocation" lowerBound="1"
        eType="#//GisRoutesHolderFromLocation" eOpposite="#//GisRoutesHolderFromLocation/ToLocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutesInfo" upperBound="-1"
        eType="#//GisRouteInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Calculated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouteInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromLocation" lowerBound="1"
        eType="#//GisLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Distance from fromLocation to toLocation, expressed in KM's"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Duration of driving from fromLocation to toLocation, expressed in hours&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToLocation" lowerBound="1"
        eType="#//GisLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WithGeometry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Geometry" upperBound="-1"
        eType="#//GisLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoded" eSuperTypes="#//GisCoordinatesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AddressGeocoded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocation" abstract="true">
    <eOperations name="getCoordinates" eType="#//GisCoordinatesAbstract"/>
    <eOperations name="addTool" eType="#//GisLocationTool">
      <eParameters name="tool" eType="#//GisToolLocation"/>
    </eOperations>
    <eOperations name="getAddToolFeedback" eType="ecore:EDataType ../../com.misc.common.moplaf.job.emf/model/job.ecore#//EnabledFeedback">
      <eParameters name="tool" eType="#//GisToolLocation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Geocoded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tools" upperBound="-1"
        eType="#//GisLocationTool" containment="true" eOpposite="#//GisLocationTool/Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoder" abstract="true"
      eSuperTypes="#//GisToolLocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouteCalculator" abstract="true"
      eSuperTypes="#//GisRouter"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressStructured" eSuperTypes="#//GisAddress">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AdministrativeArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Locality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BuildingNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressUnstructured" eSuperTypes="#//GisAddress">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouter" abstract="true">
    <eOperations name="getRoute" eType="#//GisRouteInfo">
      <eParameters name="from" lowerBound="1" eType="#//GisLocation"/>
      <eParameters name="to" lowerBound="1" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getRoutes" upperBound="-1" eType="#//GisRouteInfo">
      <eParameters name="froms" lowerBound="1" upperBound="-1" eType="#//GisLocation"/>
      <eParameters name="tos" lowerBound="1" upperBound="-1" eType="#//GisLocation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouteCalculatorOneToOne" abstract="true"
      eSuperTypes="#//GisRouteCalculator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouteCalculatorManyToMany" abstract="true"
      eSuperTypes="#//GisRouteCalculator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouteCalculatorOneToMany" abstract="true"
      eSuperTypes="#//GisRouteCalculator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouterGeodesic" eSuperTypes="#//GisRouteCalculatorOneToOne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="50.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Correction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisRouterDefaulted" eSuperTypes="#//GisRouter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimaryRouter" lowerBound="1"
        eType="#//GisRouter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SecondaryRouter" lowerBound="1"
        eType="#//GisRouter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisCoordinates" eSuperTypes="#//GisCoordinatesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisGeometry" eSuperTypes="#//GisCoordinatesAbstract"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocationPinpointed" eSuperTypes="#//GisCoordinatesAbstract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LocationPinpointed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocationPinpointer" abstract="true"
      eSuperTypes="#//GisToolLocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="GisToolLocation" abstract="true">
    <eOperations name="handle">
      <eParameters name="location" eType="#//GisLocationTool"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocationTool">
    <eOperations name="doTool"/>
    <eOperations name="flushResults"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tool" lowerBound="1" eType="#//GisToolLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" lowerBound="1"
        eType="#//GisLocation" eOpposite="#//GisLocation/Tools"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Results" upperBound="-1"
        eType="#//GisLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastHandlingFeedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DoToolFeedback" eType="ecore:EDataType ../../com.misc.common.moplaf.job.emf/model/job.ecore#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
