<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gis" nsURI="http://www.misc.com/common/moplaf/gis/model/0.1"
    nsPrefix="gis">
  <eClassifiers xsi:type="ecore:EClass" name="GisCoordinates" eSuperTypes="#//GisLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddress" abstract="true" eSuperTypes="#//GisLocation">
    <eOperations name="geocode"/>
    <eOperations name="flushGeocoded"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CountryCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geocodedAddresses" upperBound="-1"
        eType="#//GisAddressGeocoded" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedGeocodedLocation"
        eType="#//GisAddressGeocoded"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geocoder" eType="#//GisAddressGeocoder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geocodeFeedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrix">
    <eOperations name="calculate"/>
    <eOperations name="addFromLocation" eType="#//GisDistanceMatrixFromLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addToLocation" eType="#//GisDistanceMatrixToLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getFromLocation" eType="#//GisDistanceMatrixFromLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getToLocation" eType="#//GisDistanceMatrixToLocation">
      <eParameters name="location" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="getElement" eType="#//GisDistanceMatrixElement">
      <eParameters name="fromLocation" eType="#//GisLocation"/>
      <eParameters name="toLocation" eType="#//GisLocation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocations" upperBound="-1"
        eType="#//GisDistanceMatrixFromLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocations" upperBound="-1"
        eType="#//GisDistanceMatrixToLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculator" eType="#//GisDistanceMatrixCalculator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculateFeedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocation" lowerBound="1"
        eType="#//GisDistanceMatrixFromLocation" eOpposite="#//GisDistanceMatrixFromLocation/toLocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocation" lowerBound="1"
        eType="#//GisDistanceMatrixToLocation" eOpposite="#//GisDistanceMatrixToLocation/fromLocations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Calculated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixFromLocation">
    <eOperations name="getElement" eType="#//GisDistanceMatrixElement">
      <eParameters name="toLocation" eType="#//GisLocation"/>
    </eOperations>
    <eOperations name="addElement" eType="#//GisDistanceMatrixElement">
      <eParameters name="toLocation" eType="#//GisDistanceMatrixToLocation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLocations" upperBound="-1"
        eType="#//GisDistanceMatrixElement" containment="true" eOpposite="#//GisDistanceMatrixElement/fromLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//GisLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixToLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLocations" upperBound="-1"
        eType="#//GisDistanceMatrixElement" eOpposite="#//GisDistanceMatrixElement/toLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//GisLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoded" eSuperTypes="#//GisCoordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisLocation" abstract="true">
    <eOperations name="getCoordinates" eType="#//GisCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoder" abstract="true">
    <eOperations name="geocode">
      <eParameters name="address" eType="#//GisAddress"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixCalculator" abstract="true">
    <eOperations name="calculate">
      <eParameters name="matrix" eType="#//GisDistanceMatrix"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressStructured" eSuperTypes="#//GisAddress">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AdministrativeArea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Locality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BuildingNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressUnstructured" eSuperTypes="#//GisAddress">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
