<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="macroplanner" nsURI="http://www.misc.com/common/moplaf/macroplanner/model/0.1"
    nsPrefix="mp">
  <eClassifiers xsi:type="ecore:EClass" name="SupplyChainMasterData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Children" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/Parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//Product"
        eOpposite="#//Product/Children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Children" upperBound="-1"
        eType="#//Resource" eOpposite="#//Resource/Parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//Resource"
        eOpposite="#//Resource/Children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eOperations name="constructLocationProduct" eType="#//LocationProduct">
      <eParameters name="product" eType="#//Product"/>
    </eOperations>
    <eOperations name="constructLocationResource" eType="#//LocationResource">
      <eParameters name="resource" eType="#//Resource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//LocationProduct" containment="true" eOpposite="#//LocationProduct/Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//LocationResource" containment="true" eOpposite="#//LocationResource/Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Children" upperBound="-1"
        eType="#//Location" eOpposite="#//Location/Parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//Location"
        eOpposite="#//Location/Children"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/Products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" eType="#//Product"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplies" upperBound="-1"
        eType="#//Supply" eOpposite="#//Supply/LocationProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacities" upperBound="-1"
        eType="#//Capacity" eOpposite="#//Capacity/LocationProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availabilities" upperBound="-1"
        eType="#//Availability" eOpposite="#//Availability/LocationResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyChainLimits">
    <eOperations name="constructCapacity" eType="#//Capacity">
      <eParameters name="product" eType="#//LocationProduct"/>
    </eOperations>
    <eOperations name="constructAvailability" eType="#//Availability">
      <eParameters name="resource" eType="#//LocationResource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacities" upperBound="-1"
        eType="#//Capacity" containment="true" eOpposite="#//Capacity/SupplyChainLimits"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availabilities" upperBound="-1"
        eType="#//Availability" containment="true" eOpposite="#//Availability/SupplyChainLimits"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Availability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SupplyChainLimits" lowerBound="1"
        eType="#//SupplyChainLimits" eOpposite="#//SupplyChainLimits/Availabilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationResource" eType="#//LocationResource"
        eOpposite="#//LocationResource/Availabilities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enforce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Penalty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capacity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SupplyChainLimits" lowerBound="1"
        eType="#//SupplyChainLimits" eOpposite="#//SupplyChainLimits/Capacities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationProduct" eType="#//LocationProduct"
        eOpposite="#//LocationProduct/Capacities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enforce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Penalty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyChainRoutings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routings" upperBound="-1"
        eType="#//Routing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Routing">
    <eOperations name="constructRoutingProduct" eType="#//RoutingProduct">
      <eParameters name="product" eType="#//LocationProduct"/>
    </eOperations>
    <eOperations name="constructRoutingResource" eType="#//RoutingResource">
      <eParameters name="resource" eType="#//LocationResource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//RoutingResource" containment="true" eOpposite="#//RoutingResource/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//RoutingProduct" containment="true" eOpposite="#//RoutingProduct/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" lowerBound="1"
        eType="#//Routing" eOpposite="#//Routing/Products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationProduct" lowerBound="1"
        eType="#//LocationProduct"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Consumption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" lowerBound="1"
        eType="#//Routing" eOpposite="#//Routing/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationResource" eType="#//LocationResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Reservation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplyChainData">
    <eOperations name="constructSupply" eType="#//Supply">
      <eParameters name="product" eType="#//LocationProduct"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplies" upperBound="-1"
        eType="#//Supply" containment="true" eOpposite="#//Supply/SupplyChainData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supply">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SupplyChainData" lowerBound="1"
        eType="#//SupplyChainData" eOpposite="#//SupplyChainData/Supplies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationProduct" eType="#//LocationProduct"
        eOpposite="#//LocationProduct/Supplies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="To" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enforce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
