<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="macroplanner" nsURI="http://www.misc.com/common/moplaf/macroplanner/model/0.1"
    nsPrefix="mp">
  <eClassifiers xsi:type="ecore:EClass" name="Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routings" upperBound="-1"
        eType="#//Routing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Periods" upperBound="-1"
        eType="#//Period" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Routing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//RoutingResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Periods" upperBound="-1"
        eType="#//RoutingPeriod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OffsetFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OffsetTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConsumptionRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LocationResource" lowerBound="1"
        eType="#//LocationResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Reservation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Periods" upperBound="-1"
        eType="#//LocationResourcePeriod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationResourcePeriod" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LevelAtBegin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LevelAtEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Period" eType="#//Period"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Period"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingPeriod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuantityPlanned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Period" eType="#//Period"/>
  </eClassifiers>
</ecore:EPackage>
