<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="osrm" nsURI="http://www.misc.com/common/moplaf/gis/osrm/model/0.1"
    nsPrefix="osrm">
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixCalculatorOsrmOneToOne"
      eSuperTypes="../../com.misc.common.moplaf.gis.emf/model/gis.ecore#//GisRouteCalculatorOneToOne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" eType="#//Protocol"
        defaultValueLiteral="https"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="router.project-osrm.org"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="443"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/route/v1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="driving"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Overview" eType="#//Overview"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Protocol">
    <eLiterals name="Http" literal="http"/>
    <eLiterals name="Https" value="1" literal="https"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Overview">
    <eLiterals name="Simplified" literal="simplified"/>
    <eLiterals name="Full" value="1" literal="full"/>
    <eLiterals name="None" value="2" literal="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisDistanceMatrixCalculatorOsrmManyToMany"
      eSuperTypes="../../com.misc.common.moplaf.gis.emf/model/gis.ecore#//GisRouteCalculatorManyToMany">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" eType="#//Protocol"
        defaultValueLiteral="https"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="router.project-osrm.org"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="443"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/table/v1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="driving"/>
  </eClassifiers>
</ecore:EPackage>
