<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DatasetLoadDerby" nsURI="http://com.misc.common.moplaf.datasetload/derby"
    nsPrefix="loadderby">
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceJdbDerbyEmbedded" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//DataSourceJdbc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DatabasePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
