<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scheduler" nsURI="http://www.misc.com/common/moplaf/scheduler/model/0.1"
    nsPrefix="sched">
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler" abstract="true" eSuperTypes="../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Strategy">
    <eOperations name="constructScore" eType="ecore:EClass ../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Score"/>
    <eOperations name="generateTasks">
      <eParameters name="schedule" eType="#//Schedule"/>
    </eOperations>
    <eOperations name="generateResources">
      <eParameters name="schedule" eType="#//Schedule"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Schedules" upperBound="-1"
        eType="#//Schedule" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schedule" abstract="true" eSuperTypes="../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Solution">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Update the candidate solution with the parameter Move.&#xA;"/>
    </eAnnotations>
    <eOperations name="initialize">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initialiaze the solution to the zero solution (no Task is scheduled)&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="#//Task" containment="true" eOpposite="#//Task/Schedule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//Resource" containment="true" eOpposite="#//Resource/Schedule"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NrScheduledTasks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scheduler" lowerBound="1"
        eType="#//Scheduler" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Schedule" lowerBound="1"
        eType="#//Schedule" eOpposite="#//Schedule/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScheduledTasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/ScheduledResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FirstTask" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LastTask" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NrScheduledTasks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="schedule">
      <eParameters name="resource" eType="#//Resource"/>
      <eParameters name="previous" eType="#//Task"/>
      <eParameters name="next" eType="#//Task"/>
    </eOperations>
    <eOperations name="unschedule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Schedule" lowerBound="1"
        eType="#//Schedule" eOpposite="#//Schedule/Tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NextTask" eType="#//Task"
        eOpposite="#//Task/PreviousTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PreviousTask" eType="#//Task"
        eOpposite="#//Task/NextTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScheduledResource" eType="#//Resource"
        eOpposite="#//Resource/ScheduledTasks"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scheduled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveSchedule" abstract="true" eSuperTypes="../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Move">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskToSchedule" lowerBound="1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveTask" abstract="true" eSuperTypes="#//MoveSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="InsertionPoint" lowerBound="1"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleAfter" eSuperTypes="#//MoveTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleBefore" eSuperTypes="#//MoveTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unschedule" eSuperTypes="#//MoveSchedule"/>
</ecore:EPackage>
