<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="solver" nsURI="http://www.misc.com/common/moplaf/macroplanner/solver/model/0.1"
    nsPrefix="mps">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPs" upperBound="-1" eType="#//LPMacroPlanner"
        containment="true" eOpposite="#//LPMacroPlanner/Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedDataElements" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//MacroPlannerDataElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ScenarioStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ScenarioEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPMacroPlanner" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Generator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketSize" eType="ecore:EEnum ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//BucketType"
        defaultValueLiteral="Day"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Epsilon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.00001"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProductSet" lowerBound="1"
        eType="#//LPProductSet" containment="true" eOpposite="#//LPProductSet/MacroPlanner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceSet" lowerBound="1"
        eType="#//LPResourceSet" containment="true" eOpposite="#//LPResourceSet/MacroPlanner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingSet" lowerBound="1"
        eType="#//LPRoutingSet" containment="true" eOpposite="#//LPRoutingSet/MacroPlanner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" lowerBound="1"
        eType="#//Scenario" eOpposite="#//Scenario/LPs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TimeLine" eType="ecore:EClass ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//TimeLine"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CostRoutings" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CostSupplies" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CostCapacities" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CostAvailabilities" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PenaltyCapacities" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PenaltyAvailabilities"
        lowerBound="1" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solvers" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Solver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPTuple" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eOperations name="getLPMacroPlanner" eType="#//LPMacroPlanner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPTimeLine" eSuperTypes="#//LPTuple ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//ObjectWithTimeLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="LPTimeBucket" eSuperTypes="#//LPTuple ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//ObjectTimeBucket">
    <eOperations name="getBucketShortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPProductSet" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple #//LPTuple">
    <eOperations name="getProduct" eType="#//LPProduct">
      <eParameters name="locationProduct" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//LocationProduct"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MacroPlanner" lowerBound="1"
        eType="#//LPMacroPlanner" eOpposite="#//LPMacroPlanner/ProductSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//LPProduct" containment="true" eOpposite="#//LPProduct/ProductSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPProduct" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProductSet" lowerBound="1"
        eType="#//LPProductSet" eOpposite="#//LPProductSet/Products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplies" upperBound="-1"
        eType="#//LPSupply" containment="true" eOpposite="#//LPSupply/Product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacities" upperBound="-1"
        eType="#//LPCapacity" containment="true" eOpposite="#//LPCapacity/Product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//LocationProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPProductBucket" containment="true" eOpposite="#//LPProductBucket/Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPProductBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" eType="#//LPProduct"
        eOpposite="#//LPProduct/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacities" upperBound="-1"
        eType="#//LPCapacityBucket" eOpposite="#//LPCapacityBucket/ProductBucket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplies" upperBound="-1"
        eType="#//LPSupplyBucket" eOpposite="#//LPSupplyBucket/ProductBucket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consumptions" upperBound="-1"
        eType="#//LPRoutingBucketProduct" eOpposite="#//LPRoutingBucketProduct/ProductBucket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consumed" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quantity of Product&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplied" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quantity of Product&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stocked" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quantity of Product&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalcConsumed" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalcSupplied" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalcStocked" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Balance" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConsumingSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConsumptionSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StockedSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StockSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WithCapcacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StockMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CapacityTightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CapacitySlackSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SuppliedSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SupplySelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WithSupply" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SupplyMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SupplyTightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPSupply" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supply" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//Supply"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPSupplyBucket" containment="true" eOpposite="#//LPSupplyBucket/Supply"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" eType="#//LPProduct"
        eOpposite="#//LPProduct/Supplies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPSupplyBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supply" eType="#//LPSupply"
        eOpposite="#//LPSupply/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProductBucket" eType="#//LPProductBucket"
        eOpposite="#//LPProductBucket/Supplies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supplied" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fraction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPCapacity" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" lowerBound="1"
        eType="#//LPProduct" eOpposite="#//LPProduct/Capacities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacity" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//Capacity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPCapacityBucket" containment="true" eOpposite="#//LPCapacityBucket/Capacity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPCapacityBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Capacity" eType="#//LPCapacity"
        eOpposite="#//LPCapacity/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProductBucket" eType="#//LPProductBucket"
        eOpposite="#//LPProductBucket/Capacities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Stocked" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Slack" lowerBound="1" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Balance" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlackSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPResourceSet" eSuperTypes="#//LPTuple">
    <eOperations name="getResource" eType="#//LPResource">
      <eParameters name="locationResource" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//LocationResource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MacroPlanner" lowerBound="1"
        eType="#//LPMacroPlanner" eOpposite="#//LPMacroPlanner/ResourceSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//LPResource" containment="true" eOpposite="#//LPResource/ResourceSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPResource" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceSet" lowerBound="1"
        eType="#//LPResourceSet" eOpposite="#//LPResourceSet/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availabilities" upperBound="-1"
        eType="#//LPAvailability" containment="true" eOpposite="#//LPAvailability/Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//LocationResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPResourceBucket" containment="true" eOpposite="#//LPResourceBucket/Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPResourceBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="#//LPResource"
        eOpposite="#//LPResource/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availabilities" upperBound="-1"
        eType="#//LPAvailabilityBucket" eOpposite="#//LPAvailabilityBucket/ResourceBucket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reservations" upperBound="-1"
        eType="#//LPRoutingBucketResource" eOpposite="#//LPRoutingBucketResource/ResourceBucket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reserved" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quantity (number) of Resources for the duration of the bucket&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Planned" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quantity (number) of Resources for the duration of the bucket&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalcReserved" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CalcPlanned" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Balance" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReservingSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReservationSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WithAvailability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReservationMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AvailabilityTightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AvailabilitySlackSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPAvailability" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="#//LPResource" eOpposite="#//LPResource/Availabilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availability" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//Availability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPAvailabilityBucket" containment="true" eOpposite="#//LPAvailabilityBucket/Availability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPAvailabilityBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Availability" eType="#//LPAvailability"
        eOpposite="#//LPAvailability/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceBucket" eType="#//LPResourceBucket"
        eOpposite="#//LPResourceBucket/Availabilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reserved" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Slack" lowerBound="1" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Balance" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fraction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TightSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlackSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingSet" eSuperTypes="#//LPTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MacroPlanner" lowerBound="1"
        eType="#//LPMacroPlanner" eOpposite="#//LPMacroPlanner/RoutingSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routings" upperBound="-1"
        eType="#//LPRouting" containment="true" eOpposite="#//LPRouting/RoutingSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRouting" eSuperTypes="#//LPTimeLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingSet" lowerBound="1"
        eType="#//LPRoutingSet" eOpposite="#//LPRoutingSet/Routings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPRoutingBucket" containment="true" eOpposite="#//LPRoutingBucket/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//LPRoutingProduct" containment="true" eOpposite="#//LPRoutingProduct/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//LPRoutingResource" containment="true" eOpposite="#//LPRoutingResource/Routing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingProduct" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" eType="#//LPRouting"
        eOpposite="#//LPRouting/Products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Product" eType="#//LPProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingProduct" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//RoutingProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPRoutingBucketProduct" eOpposite="#//LPRoutingBucketProduct/RoutingProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingResource" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" eType="#//LPRouting"
        eOpposite="#//LPRouting/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="#//LPResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingResource" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//RoutingResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LPBuckets" upperBound="-1"
        eType="#//LPRoutingBucketResource" eOpposite="#//LPRoutingBucketResource/RoutingResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingBucket" eSuperTypes="#//LPTimeBucket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" eType="#//LPRouting"
        eOpposite="#//LPRouting/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Products" upperBound="-1"
        eType="#//LPRoutingBucketProduct" containment="true" eOpposite="#//LPRoutingBucketProduct/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//LPRoutingBucketResource" containment="true" eOpposite="#//LPRoutingBucketResource/Routing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Planned" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Rate of Routing planned (Quantity per TimeUnit)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlannedSelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="QuantitySelectedSolution"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingBucketProduct" eSuperTypes="#//LPTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProductBucket" lowerBound="1"
        eType="#//LPProductBucket" eOpposite="#//LPProductBucket/Consumptions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingProduct" eType="#//LPRoutingProduct"
        eOpposite="#//LPRoutingProduct/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" lowerBound="1"
        eType="#//LPRoutingBucket" eOpposite="#//LPRoutingBucket/Products"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LPRoutingBucketResource" eSuperTypes="#//LPTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceBucket" lowerBound="1"
        eType="#//LPResourceBucket" eOpposite="#//LPResourceBucket/Reservations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RoutingResource" eType="#//LPRoutingResource"
        eOpposite="#//LPRoutingResource/LPBuckets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routing" lowerBound="1"
        eType="#//LPRoutingBucket" eOpposite="#//LPRoutingBucket/Resources"/>
  </eClassifiers>
</ecore:EPackage>
