<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="continuous" nsURI="http://www.misc.com/common/moplaf/time/continuous/model/0.1"
    nsPrefix="timcont">
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="Hour"/>
    <eLiterals name="Second" value="1" literal="Second"/>
    <eLiterals name="Minute" value="2"/>
    <eLiterals name="Milli" value="3"/>
    <eLiterals name="Day" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Distribution" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="getDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the duration between two times in the unit of the distribution&#xA;"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getMoment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="getEventBefore" eType="#//DistributionEvent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return the latest event before&#xA; the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getEventStrictBefore" eType="#//DistributionEvent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return the latest event before&#xA; the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getEventAfter" eType="#//DistributionEvent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return the earliest event after the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getEventStrictAfter" eType="#//DistributionEvent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Return the latest event before&#xA; the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getAmountBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the value of the Distribution on the left of the given time"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getAmountAfter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the value of the Distribution at the right of the given time"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the value of the Distribution on the left of the given time"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getSlopeBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the slope of the Distribution at the left of the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getSlopeAfter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the slope at the right of the given time&#xA;"/>
      </eAnnotations>
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getMinAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the minimal amount of the Distribution between two given times&#xA;"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getMaxAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the maximal amount of the Distribution between two given times&#xA;"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getAverageAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the average amount of the Distribution between two given times&#xA;"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getCumulatedAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the integral of the amount between two given times&#xA;"/>
      </eAnnotations>
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getEarliestBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="after" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="getLatestBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="before" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="getEarliestAbove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="after" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="getLatestAbove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="before" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="getEarliestOutputPossible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eParameters name="above" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="after" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="refreshInit"/>
    <eOperations name="refreshSequence">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Refreshes all the data elements related to the sequece of events (reference SequenceEvent, DistributionEvent EventNr, Next-Previous"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="refreshChildEvent"/>
    <eOperations name="refreshProvidedEvents">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Refreshes all the data elements related to the sequece of events (reference SequenceEvent, DistributionEvent EventNr, Next-Previous"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="accept">
      <eParameters name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eParameters name="visitor" eType="#//DistributionVisitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TimeUnit" eType="#//TimeUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HorizonStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2000-01-01"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HorizonEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2099-12-31"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildEvents" upperBound="-1"
        eType="#//ChildEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SequenceEvents" upperBound="-1"
        eType="#//DistributionEvent" eOpposite="#//DistributionEvent/DistributionAsSequence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Start" lowerBound="1" eType="#//StartEvent"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="End"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="End" lowerBound="1" eType="#//EndEvent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventsProviders" upperBound="-1"
        eType="#//EventsProviderAbstract" containment="true" eOpposite="#//EventsProviderAbstract/Distribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParentDistribution" eType="#//Distribution"
        eOpposite="#//Distribution/ChildDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildDistribution" upperBound="-1"
        eType="#//Distribution" eOpposite="#//Distribution/ParentDistribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProvidedEvents" upperBound="-1"
        eType="#//DistributionEvent" eOpposite="#//DistributionEvent/DistributionAsProvidedEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistributionEvent" abstract="true" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Thing"/>
    </eAnnotations>
    <eOperations name="getAmountBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eParameters name="moment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="getAmountAfter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eParameters name="moment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="isBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//DistributionEvent"/>
    </eOperations>
    <eOperations name="isStrictBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//DistributionEvent"/>
    </eOperations>
    <eOperations name="refreshSlopeBefore"/>
    <eOperations name="refreshAmountBefore"/>
    <eOperations name="refreshAmountAfter"/>
    <eOperations name="refreshSlopeAfter"/>
    <eOperations name="refreshMoment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Moment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EventNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Next" eType="#//DistributionEvent"
        eOpposite="#//DistributionEvent/Previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Previous" eType="#//DistributionEvent"
        eOpposite="#//DistributionEvent/Next"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountAfter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeBefore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeAfter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" defaultValueLiteral=""
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DistributionAsSequence"
        eType="#//Distribution" eOpposite="#//Distribution/SequenceEvents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//Distribution"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DistributionAsProvidedEvent"
        eType="#//Distribution" eOpposite="#//Distribution/ProvidedEvents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildEvent" eSuperTypes="#//OwnedEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Original" lowerBound="1"
        eType="#//DistributionEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//OwnedEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountAtStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeAtStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//OwnedEvent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AmountImpulsion" abstract="true" eSuperTypes="#//ProvidedEvent">
    <eOperations name="refreshAmountImpulsion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountImpulsion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeImpulsion" abstract="true" eSuperTypes="#//ProvidedEvent">
    <eOperations name="refreshSlopeImpulsion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeImpulsion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmountAbsolute" abstract="true" eSuperTypes="#//ProvidedEvent">
    <eOperations name="refreshAmountAbsolute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountAbsolute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeAbsolute" abstract="true" eSuperTypes="#//ProvidedEvent">
    <eOperations name="refreshSlopeAbsolute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeAbsolute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityChangeStart" eSuperTypes="#//AmountImpulsion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//CapacityChange" eOpposite="#//CapacityChange/StartEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityChangeEnd" eSuperTypes="#//AmountImpulsion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//CapacityChange" eOpposite="#//CapacityChange/EndEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockChangeStart" eSuperTypes="#//SlopeImpulsion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//StockChange" eOpposite="#//StockChange/StartEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockChangeEnd" eSuperTypes="#//SlopeImpulsion">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="SlopeImpulsion"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//StockChange" eOpposite="#//StockChange/EndEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmountImpulsionAtomic" eSuperTypes="#//AmountImpulsion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//AmountImpulsionProvider" eOpposite="#//AmountImpulsionProvider/Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeImpulsionAtomic" eSuperTypes="#//SlopeImpulsion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//SlopeImpulsionProvider" eOpposite="#//SlopeImpulsionProvider/Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmountAbsoluteAtomic" eSuperTypes="#//AmountAbsolute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//AmountAbsoluteProvider" eOpposite="#//AmountAbsoluteProvider/Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeAbsoluteAtomic" eSuperTypes="#//SlopeAbsolute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provider" lowerBound="1"
        eType="#//SlopeAbsoluteProvider" eOpposite="#//SlopeAbsoluteProvider/Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventsProviderAbstract" abstract="true"
      eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="refreshEvents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" lowerBound="1"
        eType="#//Distribution" eOpposite="#//Distribution/EventsProviders"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventsProvider" abstract="true" eSuperTypes="#//EventsProviderAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProvidedEvents" upperBound="-1"
        eType="#//ProvidedEvent" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StockChange" eSuperTypes="#//EventsProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A change of Amount spread in a given interval of time. The amount of the Distribution increases with a given Slope during the given time interval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Slope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StartEvent" eType="#//StockChangeStart"
        containment="true" eOpposite="#//StockChangeStart/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EndEvent" eType="#//StockChangeEnd"
        containment="true" eOpposite="#//StockChangeEnd/Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityChange" eSuperTypes="#//EventsProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A change in Amount for an given interval of time. The value of the Distribution is increased by the given Amount at the start of the interval of time and decreased by the same Amount at the end of the interval of time."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StockChange"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StartEvent" eType="#//CapacityChangeStart"
        containment="true" eOpposite="#//CapacityChangeStart/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EndEvent" eType="#//CapacityChangeEnd"
        containment="true" eOpposite="#//CapacityChangeEnd/Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventProvider" abstract="true" eSuperTypes="#//EventsProviderAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProvidedEvent" eType="#//ProvidedEvent"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Moment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeImpulsionProvider" eSuperTypes="#//EventProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" eType="#//SlopeImpulsionAtomic"
        containment="true" eOpposite="#//SlopeImpulsionAtomic/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeImpulsion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SlopeAbsoluteProvider" eSuperTypes="#//EventProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" eType="#//SlopeAbsoluteAtomic"
        containment="true" eOpposite="#//SlopeAbsoluteAtomic/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlopeAbsolute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmountImpulsionProvider" eSuperTypes="#//EventProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" eType="#//AmountImpulsionAtomic"
        containment="true" eOpposite="#//AmountImpulsionAtomic/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountImpulsion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmountAbsoluteProvider" eSuperTypes="#//EventProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" eType="#//AmountAbsoluteAtomic"
        containment="true" eOpposite="#//AmountAbsoluteAtomic/Provider"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AmountAbsolute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DistributionVisitor" instanceClassName="com.misc.common.moplaf.time.continuous.DistributionVisitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="OwnedEvent" abstract="true" eSuperTypes="#//DistributionEvent">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="End"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedEvent" abstract="true" eSuperTypes="#//DistributionEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventProvider" lowerBound="1"
        eType="#//EventsProviderAbstract" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunctionDistribution" eSuperTypes="#//PropagatorFunctionDistributionAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//Distribution"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunctionDistributionEvent"
      eSuperTypes="#//PropagatorFunctionDistributionAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DistributionEvent" eType="#//DistributionEvent"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunctionEventsProvider" eSuperTypes="#//PropagatorFunctionDistributionAbstract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventsProvider" eType="#//EventsProviderAbstract"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunctionDistributionAbstract"
      eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings"/>
</ecore:EPackage>
