<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gisgisgraphy" nsURI="http://www.misc.com/common.moplaf.gisgisgraphy.emf"
    nsPrefix="gsgr">
  <eClassifiers xsi:type="ecore:EEnum" name="Protocol">
    <eLiterals name="Http" literal="http"/>
    <eLiterals name="Https" value="1" literal="https"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GisAddressGeocoderGisgraphy" eSuperTypes="../../com.misc.common.moplaf.gis.emf/model/gis.ecore#//GisAddressGeocoder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Protocol" eType="ecore:EEnum ../../com.misc.common.moplaf.gis.google.emf/model/gisgoogle.ecore#//Protocol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="80"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="maps.googleapis.com"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/maps/api/geocode/json"/>
  </eClassifiers>
</ecore:EPackage>
