/**
 */
package com.misc.common.moplaf.datatools.provider;

import com.misc.common.moplaf.datatools.util.DatatoolsAdapterFactory;
import com.misc.common.moplaf.gridview.emf.edit.IItemGridsProvider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.Disposable;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DatatoolsItemProviderAdapterFactory extends DatatoolsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the item providers created, so that they can be {@link #dispose disposed}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Disposable disposable = new Disposable();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 */
	public DatatoolsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemGridsProvider.class);
	}

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Category}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAdapter() {
		return new CategoryItemProvider(this);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.CategorizerStructuralFeature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategorizerStructuralFeatureItemProvider categorizerStructuralFeatureItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.CategorizerStructuralFeature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategorizerStructuralFeatureAdapter() {
		if (categorizerStructuralFeatureItemProvider == null) {
			categorizerStructuralFeatureItemProvider = new CategorizerStructuralFeatureItemProvider(this);
		}

		return categorizerStructuralFeatureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorTypeItemProvider extractorTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorTypeAdapter() {
		if (extractorTypeItemProvider == null) {
			extractorTypeItemProvider = new ExtractorTypeItemProvider(this);
		}

		return extractorTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorCompound} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorCompoundItemProvider extractorCompoundItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorCompound}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorCompoundAdapter() {
		if (extractorCompoundItemProvider == null) {
			extractorCompoundItemProvider = new ExtractorCompoundItemProvider(this);
		}

		return extractorCompoundItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorPipe} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorPipeItemProvider extractorPipeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorPipe}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorPipeAdapter() {
		if (extractorPipeItemProvider == null) {
			extractorPipeItemProvider = new ExtractorPipeItemProvider(this);
		}

		return extractorPipeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorUnion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorUnionItemProvider extractorUnionItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorUnion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorUnionAdapter() {
		if (extractorUnionItemProvider == null) {
			extractorUnionItemProvider = new ExtractorUnionItemProvider(this);
		}

		return extractorUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorIntersection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorIntersectionItemProvider extractorIntersectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorIntersection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorIntersectionAdapter() {
		if (extractorIntersectionItemProvider == null) {
			extractorIntersectionItemProvider = new ExtractorIntersectionItemProvider(this);
		}

		return extractorIntersectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ColumnizerAbstract} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerAbstractItemProvider columnizerAbstractItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ColumnizerAbstract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerAbstractAdapter() {
		if (columnizerAbstractItemProvider == null) {
			columnizerAbstractItemProvider = new ColumnizerAbstractItemProvider(this);
		}

		return columnizerAbstractItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Columnizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerItemProvider columnizerItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Columnizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerAdapter() {
		if (columnizerItemProvider == null) {
			columnizerItemProvider = new ColumnizerItemProvider(this);
		}

		return columnizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorPathItemProvider extractorPathItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorPathAdapter() {
		if (extractorPathItemProvider == null) {
			extractorPathItemProvider = new ExtractorPathItemProvider(this);
		}

		return extractorPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.FilterRegex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterRegexItemProvider filterRegexItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.FilterRegex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterRegexAdapter() {
		if (filterRegexItemProvider == null) {
			filterRegexItemProvider = new FilterRegexItemProvider(this);
		}

		return filterRegexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.FilterAttributeIntRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterAttributeIntRangeItemProvider filterAttributeIntRangeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.FilterAttributeIntRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterAttributeIntRangeAdapter() {
		if (filterAttributeIntRangeItemProvider == null) {
			filterAttributeIntRangeItemProvider = new FilterAttributeIntRangeItemProvider(this);
		}

		return filterAttributeIntRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.FilterAND} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterANDItemProvider filterANDItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.FilterAND}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterANDAdapter() {
		if (filterANDItemProvider == null) {
			filterANDItemProvider = new FilterANDItemProvider(this);
		}

		return filterANDItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.FilterOR} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterORItemProvider filterORItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.FilterOR}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterORAdapter() {
		if (filterORItemProvider == null) {
			filterORItemProvider = new FilterORItemProvider(this);
		}

		return filterORItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ColumnizerColumnAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerColumnAttributeItemProvider columnizerColumnAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ColumnizerColumnAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerColumnAttributeAdapter() {
		if (columnizerColumnAttributeItemProvider == null) {
			columnizerColumnAttributeItemProvider = new ColumnizerColumnAttributeItemProvider(this);
		}

		return columnizerColumnAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.NavigationReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationReferenceItemProvider navigationReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.NavigationReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationReferenceAdapter() {
		if (navigationReferenceItemProvider == null) {
			navigationReferenceItemProvider = new NavigationReferenceItemProvider(this);
		}

		return navigationReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.NavigationDowncast} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationDowncastItemProvider navigationDowncastItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.NavigationDowncast}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationDowncastAdapter() {
		if (navigationDowncastItemProvider == null) {
			navigationDowncastItemProvider = new NavigationDowncastItemProvider(this);
		}

		return navigationDowncastItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.DataToolContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataToolContextItemProvider dataToolContextItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.DataToolContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataToolContextAdapter() {
		if (dataToolContextItemProvider == null) {
			dataToolContextItemProvider = new DataToolContextItemProvider(this);
		}

		return dataToolContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Matcher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatcherItemProvider matcherItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Matcher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatcherAdapter() {
		if (matcherItemProvider == null) {
			matcherItemProvider = new MatcherItemProvider(this);
		}

		return matcherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Match} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatchItemProvider matchItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Match}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatchAdapter() {
		if (matchItemProvider == null) {
			matchItemProvider = new MatchItemProvider(this);
		}

		return matchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Columnizers} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizersItemProvider columnizersItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Columnizers}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizersAdapter() {
		if (columnizersItemProvider == null) {
			columnizersItemProvider = new ColumnizersItemProvider(this);
		}

		return columnizersItemProvider;
	}

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.CategoryAbstract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAbstractAdapter() {
		return new CategoryAbstractItemProvider(this);
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * Associates an adapter with a notifier via the base implementation, then records it to ensure it will be disposed.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void associate(Adapter adapter, Notifier target) {
		super.associate(adapter, target);
		if (adapter != null) {
			disposable.add(adapter);
		}
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		disposable.dispose();
	}

}
