/**
 */
package com.misc.common.moplaf.datatools.provider;

import com.misc.common.moplaf.datatools.util.DatatoolsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DatatoolsItemProviderAdapterFactory extends DatatoolsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DatatoolsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Categorizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategorizerItemProvider categorizerItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Categorizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategorizerAdapter() {
		if (categorizerItemProvider == null) {
			categorizerItemProvider = new CategorizerItemProvider(this);
		}

		return categorizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Category} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryItemProvider categoryItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Category}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAdapter() {
		if (categoryItemProvider == null) {
			categoryItemProvider = new CategoryItemProvider(this);
		}

		return categoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorTypeItemProvider extractorTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorTypeAdapter() {
		if (extractorTypeItemProvider == null) {
			extractorTypeItemProvider = new ExtractorTypeItemProvider(this);
		}

		return extractorTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorCompound} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorCompoundItemProvider extractorCompoundItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorCompound}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorCompoundAdapter() {
		if (extractorCompoundItemProvider == null) {
			extractorCompoundItemProvider = new ExtractorCompoundItemProvider(this);
		}

		return extractorCompoundItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractatorPipe} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractatorPipeItemProvider extractatorPipeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractatorPipe}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractatorPipeAdapter() {
		if (extractatorPipeItemProvider == null) {
			extractatorPipeItemProvider = new ExtractatorPipeItemProvider(this);
		}

		return extractatorPipeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorUnion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorUnionItemProvider extractorUnionItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorUnion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorUnionAdapter() {
		if (extractorUnionItemProvider == null) {
			extractorUnionItemProvider = new ExtractorUnionItemProvider(this);
		}

		return extractorUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorIntersection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorIntersectionItemProvider extractorIntersectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorIntersection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorIntersectionAdapter() {
		if (extractorIntersectionItemProvider == null) {
			extractorIntersectionItemProvider = new ExtractorIntersectionItemProvider(this);
		}

		return extractorIntersectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorPathItemProvider extractorPathItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorPathAdapter() {
		if (extractorPathItemProvider == null) {
			extractorPathItemProvider = new ExtractorPathItemProvider(this);
		}

		return extractorPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorOcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorOclItemProvider extractorOclItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorOcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorOclAdapter() {
		if (extractorOclItemProvider == null) {
			extractorOclItemProvider = new ExtractorOclItemProvider(this);
		}

		return extractorOclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorFilterAttributeInt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorFilterAttributeIntItemProvider extractorFilterAttributeIntItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorFilterAttributeInt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorFilterAttributeIntAdapter() {
		if (extractorFilterAttributeIntItemProvider == null) {
			extractorFilterAttributeIntItemProvider = new ExtractorFilterAttributeIntItemProvider(this);
		}

		return extractorFilterAttributeIntItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ExtractorFilterOcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtractorFilterOclItemProvider extractorFilterOclItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ExtractorFilterOcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtractorFilterOclAdapter() {
		if (extractorFilterOclItemProvider == null) {
			extractorFilterOclItemProvider = new ExtractorFilterOclItemProvider(this);
		}

		return extractorFilterOclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.CategoryCriteriaAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryCriteriaAttributeItemProvider categoryCriteriaAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.CategoryCriteriaAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryCriteriaAttributeAdapter() {
		if (categoryCriteriaAttributeItemProvider == null) {
			categoryCriteriaAttributeItemProvider = new CategoryCriteriaAttributeItemProvider(this);
		}

		return categoryCriteriaAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.CategoryCriteriaOcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryCriteriaOclItemProvider categoryCriteriaOclItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.CategoryCriteriaOcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryCriteriaOclAdapter() {
		if (categoryCriteriaOclItemProvider == null) {
			categoryCriteriaOclItemProvider = new CategoryCriteriaOclItemProvider(this);
		}

		return categoryCriteriaOclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ColumnizerExplicit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerExplicitItemProvider columnizerExplicitItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ColumnizerExplicit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerExplicitAdapter() {
		if (columnizerExplicitItemProvider == null) {
			columnizerExplicitItemProvider = new ColumnizerExplicitItemProvider(this);
		}

		return columnizerExplicitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ColumnizerColumnAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerColumnAttributeItemProvider columnizerColumnAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ColumnizerColumnAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerColumnAttributeAdapter() {
		if (columnizerColumnAttributeItemProvider == null) {
			columnizerColumnAttributeItemProvider = new ColumnizerColumnAttributeItemProvider(this);
		}

		return columnizerColumnAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.ColumnizerColumnOcl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnizerColumnOclItemProvider columnizerColumnOclItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.ColumnizerColumnOcl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnizerColumnOclAdapter() {
		if (columnizerColumnOclItemProvider == null) {
			columnizerColumnOclItemProvider = new ColumnizerColumnOclItemProvider(this);
		}

		return columnizerColumnOclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.NavigationPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationPathItemProvider navigationPathItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.NavigationPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationPathAdapter() {
		if (navigationPathItemProvider == null) {
			navigationPathItemProvider = new NavigationPathItemProvider(this);
		}

		return navigationPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.NavigationReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationReferenceItemProvider navigationReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.NavigationReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationReferenceAdapter() {
		if (navigationReferenceItemProvider == null) {
			navigationReferenceItemProvider = new NavigationReferenceItemProvider(this);
		}

		return navigationReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.NavigationDowncast} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationDowncastItemProvider navigationDowncastItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.NavigationDowncast}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationDowncastAdapter() {
		if (navigationDowncastItemProvider == null) {
			navigationDowncastItemProvider = new NavigationDowncastItemProvider(this);
		}

		return navigationDowncastItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Matcher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatcherItemProvider matcherItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Matcher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatcherAdapter() {
		if (matcherItemProvider == null) {
			matcherItemProvider = new MatcherItemProvider(this);
		}

		return matcherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.Match} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatchItemProvider matchItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.Match}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatchAdapter() {
		if (matchItemProvider == null) {
			matchItemProvider = new MatchItemProvider(this);
		}

		return matchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.misc.common.moplaf.datatools.DataTools} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataToolsItemProvider dataToolsItemProvider;

	/**
	 * This creates an adapter for a {@link com.misc.common.moplaf.datatools.DataTools}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataToolsAdapter() {
		if (dataToolsItemProvider == null) {
			dataToolsItemProvider = new DataToolsItemProvider(this);
		}

		return dataToolsItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (categorizerItemProvider != null) categorizerItemProvider.dispose();
		if (categoryItemProvider != null) categoryItemProvider.dispose();
		if (extractorTypeItemProvider != null) extractorTypeItemProvider.dispose();
		if (extractorCompoundItemProvider != null) extractorCompoundItemProvider.dispose();
		if (extractatorPipeItemProvider != null) extractatorPipeItemProvider.dispose();
		if (extractorUnionItemProvider != null) extractorUnionItemProvider.dispose();
		if (extractorIntersectionItemProvider != null) extractorIntersectionItemProvider.dispose();
		if (extractorPathItemProvider != null) extractorPathItemProvider.dispose();
		if (extractorOclItemProvider != null) extractorOclItemProvider.dispose();
		if (extractorFilterAttributeIntItemProvider != null) extractorFilterAttributeIntItemProvider.dispose();
		if (extractorFilterOclItemProvider != null) extractorFilterOclItemProvider.dispose();
		if (categoryCriteriaAttributeItemProvider != null) categoryCriteriaAttributeItemProvider.dispose();
		if (categoryCriteriaOclItemProvider != null) categoryCriteriaOclItemProvider.dispose();
		if (columnizerExplicitItemProvider != null) columnizerExplicitItemProvider.dispose();
		if (columnizerColumnAttributeItemProvider != null) columnizerColumnAttributeItemProvider.dispose();
		if (columnizerColumnOclItemProvider != null) columnizerColumnOclItemProvider.dispose();
		if (navigationPathItemProvider != null) navigationPathItemProvider.dispose();
		if (navigationReferenceItemProvider != null) navigationReferenceItemProvider.dispose();
		if (navigationDowncastItemProvider != null) navigationDowncastItemProvider.dispose();
		if (matcherItemProvider != null) matcherItemProvider.dispose();
		if (matchItemProvider != null) matchItemProvider.dispose();
		if (dataToolsItemProvider != null) dataToolsItemProvider.dispose();
	}

}
