<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="file" nsURI="http://www.misc.com/common/moplaf/file/model/0.1"
    nsPrefix="file">
  <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileLocal" eSuperTypes="#//ByteFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileRemote" eSuperTypes="#//ByteFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileInMemory" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileReaderWriter" abstract="true" eSuperTypes="#//FileHandler">
    <eOperations name="getReadFeedback" eType="#//EnabledFeedback">
      <eParameters name="file" eType="#//File"/>
    </eOperations>
    <eOperations name="getWriteFeedback" eType="#//EnabledFeedback">
      <eParameters name="file" eType="#//File"/>
    </eOperations>
    <eOperations name="readFile"/>
    <eOperations name="writeFile"/>
    <eOperations name="close"/>
    <eOperations name="readFile">
      <eParameters name="file" eType="#//File"/>
    </eOperations>
    <eOperations name="writeFile">
      <eParameters name="file" eType="#//File"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReadFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WriteFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CloseFeedback" eType="#//EnabledFeedback"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EnabledFeedback" instanceClassName="com.misc.common.moplaf.common.EnabledFeedback"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileHandler" abstract="true" eSuperTypes="#//FileOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedFile" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HandledFile" eType="#//File"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Files" upperBound="-1"
        eType="#//File" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Files" eSuperTypes="#//FileOwner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ByteFile" abstract="true" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Encoding" eType="#//FileEncoding"
        defaultValueLiteral="UTF-8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileOutput" abstract="true" eSuperTypes="#//FileOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutputFile" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FileEncoding">
    <eLiterals name="US_ASCII" value="1" literal="US-ASCII"/>
    <eLiterals name="ISO_8859_1" value="2" literal="ISO-8859-1"/>
    <eLiterals name="UTF_8" value="3" literal="UTF-8"/>
    <eLiterals name="UTF_16" value="4" literal="UTF-16"/>
    <eLiterals name="UTF_16BE" value="5" literal="UTF-16BE"/>
    <eLiterals name="UTF_16LE" value="6" literal="UTF-16LE"/>
  </eClassifiers>
</ecore:EPackage>
