<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dbsynch" nsURI="//www.misc.com/common/moplaf/dbsynch/model/0.1"
    nsPrefix="dbs">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The method refresh() is called by the framework when changed by the framework, so when changed after a read action"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" eSuperTypes="#//DbSynchUnitAbstract">
    <eOperations name="connect"/>
    <eOperations name="disconnect"/>
    <eOperations name="synchDownTableImpl">
      <eParameters name="table" eType="#//Table"/>
    </eOperations>
    <eOperations name="synchUpTableImpl">
      <eParameters name="table" eType="#//Table"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Connected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceJdbc" eSuperTypes="#//DataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataBaseUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataBaseUserPwd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefaultSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbSynchUnitAbstract" abstract="true">
    <eOperations name="refreshMetaData"/>
    <eOperations name="synchUp">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load the tables in the group, update the rows accordingly (synchronize the application data as a function of what is read)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="synchDown">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load the tables in the group, update the rows accordingly (synchronize the application data as a function of what is read)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getParamValue" eType="#//Object">
      <eParameters name="attribute" eType="#//EAttribute"/>
    </eOperations>
    <eOperations name="getParamAttributes" upperBound="-1" eType="#//Object"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tables" upperBound="-1"
        eType="#//Table" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataSource" eType="#//DataSource"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildUnits" upperBound="-1"
        eType="#//DbSynchUnitAbstract" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DbSynchUnit" abstract="true" eSuperTypes="#//DbSynchUnitAbstract">
    <eOperations name="refresh">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Make sure the derived elements are up to date"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParentUnit" lowerBound="1"
        eType="#//DbSynchUnitAbstract" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" abstract="true">
    <eOperations name="addColumn">
      <eParameters name="Key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" eType="#//EnumColumnType"/>
      <eParameters name="attribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    </eOperations>
    <eOperations name="addParam">
      <eParameters name="dbSynchAttribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    </eOperations>
    <eOperations name="refreshMetaData"/>
    <eOperations name="synchDown">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Write in the tables as a function of the changes in the applicative data since the last synchDown"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="synchUp">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load the tables in the group, update the rows accordingly (synchronize the application data as a function of what is read)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="refresh"/>
    <eOperations name="getRow" eType="#//TableRow">
      <eParameters name="key" eType="#//TableRowKey"/>
    </eOperations>
    <eOperations name="constructRow" eType="#//TableRow"/>
    <eOperations name="addRow">
      <eParameters name="row" eType="#//TableRow"/>
    </eOperations>
    <eOperations name="removeRow">
      <eParameters name="row" eType="#//TableRow"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SynchUnit" lowerBound="1"
        eType="#//DbSynchUnitAbstract" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Columns" upperBound="-1"
        eType="#//TableColumn" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="KeyColumns" upperBound="-1"
        eType="#//TableColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataColumns" upperBound="-1"
        eType="#//TableColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WhereClause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParamDbSynchUnitAttributes"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Rows" upperBound="-1" eType="#//TableRow"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectSqlStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InsertSqlStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpdateSqlStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeleteSqlStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumberOfRows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastSynchDown" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastSynchUp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ColumnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RowAttribute" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ColumnType" eType="#//EnumColumnType"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow" abstract="true">
    <eOperations name="refresh"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Table" eType="#//Table"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key" eType="#//TableRowKey"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldKey" eType="#//TableRowKey"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Deleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldDeleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModificationLastSynchUp"
        eType="#//EnumModification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModificationNextSynchDown"
        eType="#//EnumModification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumModification">
    <eLiterals name="ENUM_MODIFICATION_NONE" literal="None"/>
    <eLiterals name="ENUM_MODIFICATION_CREATE" literal="Create"/>
    <eLiterals name="ENUM_MODIFICATION_UPDATE" literal="Update"/>
    <eLiterals name="ENUM_MODIFICATION_DELETE" literal="Delete"/>
    <eLiterals name="ENUM_MODIFICATION_MUTATEKEY" value="4" literal="MutateKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumColumnType">
    <eLiterals name="ENUM_COLUMN_TYPE_INT" value="1" literal="Int"/>
    <eLiterals name="ENUM_COLUMN_TYPE_FLOAT" value="2" literal="Float"/>
    <eLiterals name="ENUM_COLUMN_TYPE_CHAR" value="3" literal="Char"/>
    <eLiterals name="ENUM_COLUMN_TYPE_DATE" value="4" literal="Date"/>
    <eLiterals name="ENUM_COLUMN_TYPE_TIME" value="5" literal="Time"/>
    <eLiterals name="ENUM_COLUMN_TYPE_DATETIME" value="6" literal="DateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EAttribute" instanceClassName="org.eclipse.emf.ecore.EAttribute"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TableRowKey" instanceClassName="com.misc.common.moplaf.dbsynch.impl.TableRowKeyImpl"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
</ecore:EPackage>
