<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spreadsheetpoi" nsURI="http://www.misc.com/common/moplaf/spreadsheet/poi/model/0.1"
    nsPrefix="spshpoi">
  <eClassifiers xsi:type="ecore:EClass" name="SpreadsheetPOI" eSuperTypes="../../com.misc.common.moplaf.spreadsheet.emf/model/spreadsheet.ecore#//Spreadsheet"/>
</ecore:EPackage>
