<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="propagator2" nsURI="http://www.misc.com/common/moplaf/propagator2/model/0.1"
    nsPrefix="prg">
  <eClassifiers xsi:type="ecore:EClass" name="ObjectWithPropagatorFunctions">
    <eOperations name="addPropagatorFunction">
      <eParameters name="propagatorFunction" eType="#//PropagatorFunction"/>
    </eOperations>
    <eOperations name="getPropagatorFunction" eType="#//PropagatorFunction">
      <eParameters name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="addPropagatorFunctions">
      <eParameters name="factoryID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PropagatorFunctions" upperBound="-1"
        eType="#//PropagatorFunction" containment="true" eOpposite="#//PropagatorFunction/ObjectWithPropagatorFunctions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunction">
    <eOperations name="init"/>
    <eOperations name="enable"/>
    <eOperations name="disable"/>
    <eOperations name="reset"/>
    <eOperations name="touch">
      <eParameters name="toucher" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="untouch"/>
    <eOperations name="refreshAntecedents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="refreshThis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="refreshChildrenAndThis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="refresh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="doGetAntecedents" upperBound="-1" eType="#//PropagatorFunction"/>
    <eOperations name="doGetParent" eType="#//PropagatorFunction"/>
    <eOperations name="doRefresh"/>
    <eOperations name="doRefresh">
      <eParameters name="toucher" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getScope" eType="#//PropagatorFunction"/>
    <eOperations name="getFactoryID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//PropagatorFunction"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Antecedents" upperBound="-1"
        eType="#//PropagatorFunction" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntecedentsSibling" upperBound="-1"
        eType="#//PropagatorFunction" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Touched" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TouchedChildren" upperBound="-1"
        eType="#//PropagatorFunction" eOpposite="#//PropagatorFunction/TouchedParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Touchers" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObjectWithPropagatorFunctions"
        lowerBound="1" eType="#//ObjectWithPropagatorFunctions" transient="true" eOpposite="#//ObjectWithPropagatorFunctions/PropagatorFunctions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Instance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TouchedParent" eType="#//PropagatorFunction"
        eOpposite="#//PropagatorFunction/TouchedChildren"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagatorFunctionBindings" eSuperTypes="#//PropagatorFunction">
    <eOperations name="doGetBindings" eType="#//Bindings"/>
    <eOperations name="doCollectExplicitAntecedents">
      <eParameters name="antecedents" upperBound="-1" eType="#//PropagatorFunction"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bindings" instanceClassName="com.misc.common.moplaf.propagator2.util.Bindings"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Notification" instanceClassName="org.eclipse.emf.common.notify.Notification"/>
</ecore:EPackage>
