<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jobxmlrpc" nsURI="//www.misc.com/common/moplaf/job/client/xmlrpc/model/0.1"
    nsPrefix="jbx">
  <eClassifiers xsi:type="ecore:EClass" name="JobEngineClient" eSuperTypes="../../com.misc.common.moplaf.job.client.emf/model/jobclient.ecore#//JobEngine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="localhost"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8080"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="xmlrpc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobEngineServer" eSuperTypes="../../com.misc.common.moplaf.job.client.emf/model/jobclient.ecore#//JobSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8080"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="xmlrpc"/>
  </eClassifiers>
</ecore:EPackage>
